### ISSUE TITLE
Error when using plugin with response headers

### ISSUE THREAD

**Issue by Paul-Oginni** [jef-srl/sereverless-aws-response-schema#1]
This is an awesome plugin!

However, I'm getting the following error when I try to it while configuring response headers:

```
Invalid mapping expression parameter specified: method.response.header.Content-Type
```

This is what the function configuration looks like in `serverless.yml`:

```
functions:
  func_name:
    handler: lib/lambdas/router/router-function.handler
    events:
      - http:
          path: api/path/{id}
          method: get
          authorizer:
            name: auth_function
            identitySource: "method.request.header.X-Api-Key"
            resultTtlInSeconds: 0
          private: true
          integration: lambda
          reqValidatorName: ParameterRequestValidator
          request:
            schemas:
              application/json: ${file(./lib/model-options/request_model.json)}
          responseSchemas:
            200: 
              application/json: ${file(lib/model-options/response_model.json)}
          response:
            statusCodes:
              200:
                pattern: '' # JSON response
                headers:
                  Content-Type: "'true'"
```

Have I configured something incorrectly?

Thank you!
